@BookTracker.Api_HostAddress = http://localhost:5015

### Get Books
GET http://localhost:5015/books

###

### Create Book
POST http://localhost:5015/books
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

###

### Create Book
POST http://localhost:5015/books
Content-Type: application/json

{
  "title": "Tender Is the Night",
  "author": "F. Scott Fitzgerald",
  "year": 1934
}

### Update Book
PUT http://localhost:5015/books/6
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

### Update non-existing Book
PUT http://localhost:5015/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}

### Delete Book
DELETE  http://localhost:5015/books/6

###

###