@BookTracker.Api_HostAddress = http://localhost:5015

### Get Books
GET http://localhost:5015/books

###

### Get Book by Id
GET http://localhost:5015/books/7

###

### Get Book by non-existing Id
GET http://localhost:5015/books/70

###

### Create Book
POST http://localhost:5015/books
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

###

### Create Book
POST http://localhost:5015/books
Content-Type: application/json

{
  "title": "Tender Is the Night",
  "author": "F. Scott Fitzgerald",
  "year": 1934
}

### Update Book
PUT http://localhost:5015/books/6
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

### Update non-existing Book
PUT http://localhost:5015/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}

### Delete Book
DELETE  http://localhost:5015/books/6

###

### Get Books Page 1
GET http://localhost:5015/books?page=1&pageSize=10

### Get Books Page 2
GET http://localhost:5015/books?page=2&pageSize=10

### Search Books
GET http://localhost:5015/books?search=octopus

### Search Books With Paging
GET http://localhost:5015/books?search=octopus&page=1&pageSize=5

###

### Get Members
GET http://localhost:5015/members

### Create Member
POST http://localhost:5015/members
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@example.com"
}

### Get Member Details
GET http://localhost:5015/members/1

### Update Member
PUT http://localhost:5015/members/1
Content-Type: application/json

{
  "name": "Ada Byron",
  "email": "ada.byron@example.com"
}

### Delete Member
DELETE http://localhost:5015/members/1

### Create member with credentials
POST http://localhost:5015/members
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@example.com",
  "password": "analytical-engine"
}